apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app4
  template:
    metadata:
      labels:
        app: springboot-app4
    spec:
      containers:
        - name: springboot-app4
          image: ghcr.io/depak1067/myapp:${{ github.sha }}
          ports:
            - containerPort: 8080
