apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app5
  template:
    metadata:
      labels:
        app: springboot-app5
    spec:
      containers:
        - name: springboot-app5
          image: ghcr.io/depak1067/myapp/myimage:${{ github.sha }}
          ports:
            - containerPort: 8080
