apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app1
  template:
    metadata:
      labels:
        app: springboot-app1
    spec:
      containers:
        - name: springboot-app1
          image: ghcr.io/depak1067/my-app:${{ github.sha }}
          ports:
            - containerPort: 8080
