apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service2
spec:
  type: LoadBalancer
  selector:
    app: springboot-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
