apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service1
spec:
  type: LoadBalancer
  selector:
    app: springboot-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
